services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: imam_datasub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - imam_datasub_pg:/var/lib/postgresql/data

volumes:
  imam_datasub_pg:
